# Generated by Django 5.1.4 on 2024-12-17 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Explore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='pics')),
                ('rating', models.CharField(max_length=30)),
                ('ex_type', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('review', models.CharField(max_length=30)),
                ('offer', models.BooleanField(default=False)),
            ],
        ),
    ]
