# Generated by Django 5.1.4 on 2024-12-17 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='explore',
            name='pr_range',
            field=models.CharField(default='$10-50', max_length=30),
            preserve_default=False,
        ),
    ]
